[tox]
minversion = 1.6
envlist = py27, flake8, doc

[testenv]
basepython=python2.7
setenv = VIRTUAL_ENV={envdir}
usedevelop = True
deps = -r{toxinidir}/test-requirements.txt
commands = pytest {posargs}

[testenv:venv]
commands = {posargs}

[testenv:doc]
deps = -r{toxinidir}/docs/requirements.txt
commands = sphinx-build -W -b html docs/ docs/_build/html

[testenv:flake8]
commands = flake8 {posargs}
# No need to install any other dependency
deps = flake8

[flake8]
count=1
show-pep8=1
show-source=1
statistics=1
exclude = .git,.tox,__pycache__,build,docs,dist,scap/sh.py,bin

[pytest]
addopts = --cov=scap --cov-report=html --doctest-modules --cov-branch
